### ISSUE TITLE
handlerInput.requestEnvelope.intent.slots.year.value is not working 

### ISSUE THREAD

**Issue by ghost** [alexa/skill-sample-nodejs-first-skill#25]
It seems to be that code has been altered to Alexa.get  like that but cannot find that correctly.
For me its working until getting all three variables but not storing it and responding.
[birthday intent.txt](https://github.com/alexa/skill-sample-nodejs-first-skill/files/4023482/birthday.intent.txt)

**Comment by JoeMoCode** [comment]
Hi Jayananden, the code you attached is not storing the slot values. Once the session ends, all session attributes are cleared. Check out this section where the persistent attributes are used. https://github.com/alexa/skill-sample-nodejs-first-skill/blob/master/final/index.js#L114
