### ISSUE TITLE
memory is not deleted if skill is re-created in same account

### ISSUE THREAD

**Issue by PawanMude** [alexa/skill-sample-nodejs-first-skill#27]
i create "birthday wishes" and while testing enter birthday. 
Then I deleted "cake walk one". 

I created "cake walk" ; while testing it's giving old message. "Welcome back. It looks like there are xxx days until your xxxth birthday."

Also text changed in languageString.js is not working; it's showing old text.

**Comment by JoeMoCode** [comment]
Hey PawanMude, Sometimes the console will have the context from the old session if you never specifically ended it. Try stopping the session with "stop" or "quit". Then, refresh the console. You should see JSON request and response if you are hitting one of your skill backends and you can double check with the logs. 

If you have further issues around this, try http://alexa.design/contactus
