### ISSUE TITLE
"Create an Alexa Skill in 5 Minutes" documentation missing steps 

### ISSUE THREAD

**Issue by JeffreyOI** [alexa/skill-sample-nodejs-first-skill#32]
Hello I am working through the tutorial for this skill. I am currently on step three, "Create a Skill in Five Minutes": https://developer.amazon.com/en-US/alexa/alexa-skills-kit/get-deeper/tutorials-code-samples/build-an-engaging-alexa-skill/module-3. While doing so, I have noticed that a step is missing/incorrect. 

When a new skill is created, it is set with the invocation "change me". In order for Step 4c to work, the invocation needs to be changed to "cake time".

**Comment by liammarcovitz** [comment]
That's true, I had to spend an hour figuring that out.

**Comment by aszk** [comment]
Thank you for the feedback. The page has been restructured and links shouldn't be broken. Please let me know if you still can find the broken link.
